### ISSUE TITLE
Nix Package?

### ISSUE THREAD

**Issue by noctuid** [malcolmstill/cl-libinput#1]
I wanted to try this out. If I clone the repo to my local projects and run `(ql:quickload "cl-libinput")`, I get the following error during compilation:

```
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Package NIX does not exist.
;   
;       Line: 125, Column: 15, File-Position: 3733
```

What is the nix package?

**Comment by malcolmstill** [comment]
`cl-libinput` depends on `osicat` which defines the `NIX` package.

```
(ql:quickload "osicat")
(ql:quickload "cl-libinput")
```

...should hopefully work. Let me know if it doesn't.

**Comment by noctuid** [comment]
I added `#:osicat` to the `:depends-on` in the asd file, and it loads fine now. However, when I eval the example code, I get the error `Symbol "WITH-POLLFDS" not found in the OSICAT-POSIX package.`. I don't see `with-pollfds` or anything really similar exported in the nix package [here](https://github.com/osicat/osicat/blob/master/posix/packages.lisp) either. Maybe the name has changed?

**Comment by malcolmstill** [comment]
Ah, I see the problem. The example code doesn't work...I had submitted a pull request to osicat to add the polling stuff. It hasn't been accepted yet so that won't actually work. However I wrote some code in the meantime in [ulubis](https://github.com/malcolmstill/ulubis).

As a quick fix you can add the following to your code:

```
(defconstant pollin 1)
(defconstant pollpri 2)
(defconstant pollout 4)
(defconstant pollerr 8)
(defconstant pollhup 16)
(defconstant pollnval 32)

(defcstruct pollfd
  (fd :int)
  (events :short)
  (revents :short))

(defcfun ("poll" %poll) :int
  (fds     :pointer)
  (nfds    :unsigned-long)
  (timeout :int))

(defun poll (pollfds nfds timeout)
  "Wait for events on file descriptors defined by POLLFDS. TIMEOUT is the time in milliseconds to wait for activity; a TIMEOUT of -1 will block indefinitely, a TIMEOUT of 0 will return immediately"
  (let ((r (%poll pollfds nfds timeout)))
    (when (= r -1)
      (nix:posix-error))
    (> r 0)))
    
(defun poll-return-event (pollfd)
  "Access REVENT of pollfd struct"
  (with-foreign-slots ((revents) pollfd (:struct pollfd))
    revents))

(defmacro with-pollfds ((name &rest specs) &body body)
  (let ((nfds (length specs)))
    `(with-foreign-object (,name '(:struct pollfd) ,nfds)
       (let (,@(loop :for i :from 0 :to (- nfds 1)
                  :collecting (let ((spec (nth i specs)))
                        `(,(first spec) (mem-aptr ,name '(:struct pollfd) ,i)))))
         ,@(loop :for i :from 0 :to (- nfds 1)
              :collecting (let ((spec (nth i specs)))
                    `(with-foreign-slots ((fd events revents) ,(first spec) (:struct pollfd))
                       (setf fd ,(second spec))
                       (setf events (logior ,@(rest (rest spec))))
                       (setf revents 0))))
         ,@body))))
```
...and remove the `NIX:` prefix. (you can see the code in [https://github.com/malcolmstill/ulubis/blob/master/syscall.lisp](https://github.com/malcolmstill/ulubis/blob/master/syscall.lisp))

I will update the example at some point.

**Comment by noctuid** [comment]
Thank you, that fixes the errors.
